//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LainausjarjestelmaMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Esineet
    {
        public int EsineID { get; set; }
        public string EsineenNimi { get; set; }
        public string Lainaaja { get; set; }
        public Nullable<System.DateTime> LainausPaiva { get; set; }
        public Nullable<System.DateTime> PalautusPaiva { get; set; }
        public string Omistaja { get; set; }
        public string ImageLink { get; set; }
    }
}
